# Generated by Django 3.2.16 on 2023-07-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, null=True)),
                ('detail', models.TextField(max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
                'db_table': 'research',
            },
        ),
    ]
