# Generated by Django 3.2.16 on 2023-07-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='positionType',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
