# Generated by Django 3.2.16 on 2023-07-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0003_auto_20230706_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='interest',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
