# Generated by Django 3.2.16 on 2023-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(default='#', upload_to='publication/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
