# Generated by Django 3.2.16 on 2023-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='#', upload_to='news/')),
                ('title', models.TextField(max_length=200, null=True)),
                ('text', models.TextField(max_length=5000, null=True)),
                ('time', models.TextField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
    ]
